IDAT entry_point.
NCI-CGR/GwasQcPipeline pull request #359
Opened 2024-11-25 20:21 UTC by rajwanir

This PR adds IDAT entry_point and makes the workflow truly raw data to QC report.

1.  The IDAT entry point uses a Illumina's free Dragena software (https://help.dragenarray.illumina.com/product-guides/dragen-array-local-analysis) for converting IDAT to GTC (383b89bd5225808973a47c9357136d8339b60c0e). Since Dragena is Illumina's proprietary software and unavailable via Conda, the pipliene can only use it as an enviornment module.
2. Non-CCAD2 users can download the dragen array from Illumina's website and provide a path to dragena binary via the `dragena_location` option in config to use the IDAT entry_point (see 55655f629fa30a8a35918fa657636a334973353b). 
3. After IDAT to GTC conversion, the workflow resumes GTC entry point with either BCF or PED option. (13cf63d21eb2f996b977bb345f0b38ee4b493ec5)
4. The IDAT entry point can run both locally and in cluster_mode (13cf63d21eb2f996b977bb345f0b38ee4b493ec5)

I can update the docs once PR is finalized. Thank you.

2024-11-26 20:50 UTC, jaamarks commented
Concept ACK - will test.

2025-02-07 19:57 UTC, jaamarks reviewed
I generally agree with these changes. The will enhance the generality of the pipeline and effectively address several edge cases for specific chips. 

I have a series of tests planned, but I'm currently waiting in the queue for CCAD2. I will update you with the results once the tests are complete.

Nice work 👍

2025-02-07 19:57 UTC, jaamarks commented on src/cgr_gwas_qc/workflow/modules/idat.smk
> +    threads: 44
This could benefit from your approach in PR #361

2025-02-07 19:57 UTC, jaamarks commented on src/cgr_gwas_qc/workflow/modules/idat.smk
> +        $dragena genotype call --bpm-manifest {params.bpm} --cluster-file {params.egt} --idat-sample-sheet {input.idat_ss} --num-threads {threads} --output-folder {output.output_folder}
I think we could add another check to handle the case when dragena is not available. For example wrong path to executable.
```

if ! command -v $dragena &> /dev/null; then
    echo "Error: Dragena executable not found. Ensure that 'dragena/1.0.0' module is loaded or provide a valid 'dragena_location' in the config." >&2
    exit 1
fi

```

2025-02-10 17:47 UTC, jaamarks requested changes
I noticed that in `cgr_gwas_qc/models/config/reference_files.py` the docstring for ReferenceFiles class is missing `illumina_cluster_file`. This affects the docs. Can you add this into your PR?

2025-02-10 19:25 UTC, rajwanir commented
> I noticed that in `cgr_gwas_qc/models/config/reference_files.py` the docstring for ReferenceFiles class is missing `illumina_cluster_file`. This affects the docs. Can you add this into your PR?

Added in d25604d13cad6c4cde6971c47bcae14b25b12ff1.

2025-02-10 19:26 UTC, rajwanir commented on src/cgr_gwas_qc/workflow/modules/idat.smk
> +        $dragena genotype call --bpm-manifest {params.bpm} --cluster-file {params.egt} --idat-sample-sheet {input.idat_ss} --num-threads {threads} --output-folder {output.output_folder}
Thanks for the suggestion.

Added in 3e4469ff40c593b3f818c0415f59b9821308bc83

2025-02-10 19:31 UTC, rajwanir commented on src/cgr_gwas_qc/workflow/modules/idat.smk
> +    threads: 44
Agree, it would. But PR #361 is yet to be merged. How about we merge this and add a commit later to replace `threads: 44` with `threads: workflow.cores` once  PR #361 is merged. Thanks

2025-02-13 22:11 UTC, jaamarks approved these changes
Everything looks good! We tested this PR using a sample size of N=500, and the summary tables matched the results from previous runs that did not include this feature. 

After reviewing all aspects and confirming the successful execution of the GitHub Actions test_and_build job, I approve this PR.

2025-02-13 22:11 UTC, merged