Reduces memory usage and time for plink rule genome.
NCI-CGR/GwasQcPipeline pull request #363
Opened 2024-12-02 15:36 UTC by rajwanir

# Description:
This PR reduces memory usage and time for plink rule genome. 

1. It builds on the PR #361 and assigns the threads as `workflow.cores` which reduces time.
2. It introduces .genome computation in batches and controls the batches executed simultaneously to reduce memory usage.

# Testing:
It reduces the compute time for `sample_level_ibd` to about 110 min with 12Gb memory used for a sample size of 123,244. The same efficiency gains should apply to rule `population_level_ibd`.

2025-02-25 23:05 UTC, jaamarks requested changes

2025-02-25 23:05 UTC, jaamarks commented on src/cgr_gwas_qc/workflow/sub_workflows/subject_qc.smk
> +        n_tasks=floor(max(1, workflow.cores / min(10, workflow.cores))),
The `ceil` and `floor` functions need to be imported into the `subject_qc.smk` file so that we can use them without the `math.` prefix (like how you did with the `sample_qc.smk` file. Else, you will get an error like this:
```
NameError in line 277 of .../GwasQcPipeline/src/cgr_gwas_qc/workflow/sub_workflows/subject_qc.smk:
name 'ceil' is not defined
  File ".../GwasQcPipeline/src/cgr_gwas_qc/workflow/Snakefile", line 85, in <module>
  File ".../GwasQcPipeline/src/cgr_gwas_qc/workflow/sub_workflows/subject_qc.smk", line 277, in <module>
sex_chr_included  True
```

2025-02-25 23:05 UTC, jaamarks commented on src/cgr_gwas_qc/workflow/sub_workflows/subject_qc.smk
The `ceil` and `floor` functions need to be imported into the `subject_qc.smk` file so that we can use them without the `math.` prefix (like how you did with the `sample_qc.smk` file. Else, you will get an error like this:
```
NameError in line 277 of .../GwasQcPipeline/src/cgr_gwas_qc/workflow/sub_workflows/subject_qc.smk:
name 'ceil' is not defined
  File ".../GwasQcPipeline/src/cgr_gwas_qc/workflow/Snakefile", line 85, in <module>
  File ".../GwasQcPipeline/src/cgr_gwas_qc/workflow/sub_workflows/subject_qc.smk", line 277, in <module>
sex_chr_included  True
```

2025-02-26 15:54 UTC, rajwanir commented on src/cgr_gwas_qc/workflow/sub_workflows/subject_qc.smk
> +        n_tasks=floor(max(1, workflow.cores / min(10, workflow.cores))),
Imported in 46a2f26dcac4d06ba89b91b85ce110d34a2a4073. Thanks.

2025-02-26 19:29 UTC, jaamarks approved these changes
LGTM

All tests have passed and improved metrics on both population- and sample-level IBD steps.

2025-02-26 19:30 UTC, merged