Skip King and Graf concordance checks.
NCI-CGR/GwasQcPipeline pull request #367
Opened 2024-12-11 18:58 UTC by rajwanir

This PR adds a `concordance_tools`  option in in workflow_prams to control whether graf and king concordance checks should be executed:

1. If `workflow_prams.concordance_tools.graf` is False, rules `graf_extract_fingerprint_snps`  and `sample_concordance_graf` will be skipped from execution in sample_qc.
2. If `workflow_prams.concordance_tools.king` is False, rule `sample_concordance_king` will be skipped from execution in sample_qc.

The output of above rules were not used by `sample_concordance.py` after PR https://github.com/NCI-CGR/GwasQcPipeline/pull/310 so graf and king file are removed from rule `sample_concordance_summary` as inputs to reflect that.

No changes in QC report. The output of these rules are currently for reference purpose only. Not used by any rules downstream.

resolves #364 .

2025-02-25 19:45 UTC, jaamarks requested changes
Nicely done. This adds a nice new feature and the refactoring was much needed. Makes it a lot easier to read and maintain. 

The tests I have conducted show that the new features work as expected. 

Please ensure that we have documentation that details how only the sample_qc subworkflow will execute now if concordance_tools.plink = false.

Also incorporate a few of the corrections I recommended for the field descriptions.
Thanks -j

2025-02-25 19:45 UTC, jaamarks commented on src/cgr_gwas_qc/models/config/workflow_params.py
> +        description="Is graf relatedness results needed? Even if True, the results won't be used in sample_concordance.",
Correction: "**Are** Graf relatedness results needed? ..."

2025-02-25 19:45 UTC, jaamarks commented on src/cgr_gwas_qc/models/config/workflow_params.py
> +        description="Is king relateness results needed? Even if True, the results won't be used in sample_concordance.",
Correction: "**Are** king relatedness results needed? Even if set to True, the results won't be used in sample_concordance."

2025-02-25 19:45 UTC, jaamarks commented on src/cgr_gwas_qc/models/config/workflow_params.py
>      """This set of parameters control what parts and how the workflow is run.
Update to this: "This set of parameters controls which parts of the workflow are run and how they are executed."

2025-02-25 19:45 UTC, jaamarks commented on src/cgr_gwas_qc/models/config/workflow_params.py
> +        "Please note if even graf and king reledness checks are requested and executed, these would be for reference purpose only and not considered sample_concordance_summary.",
Update to "Please note **even if** graf and king **relatedness** checks..."

2025-02-25 19:45 UTC, jaamarks commented on src/cgr_gwas_qc/models/config/workflow_params.py
> +        description="Is plink ibd relateness results needed? It is the primary tool used in sample_qc report. If false, no replicate/relatedness check would be considered in sample_qc",
Correction: "**Are** plink..."

2025-02-25 19:45 UTC, jaamarks commented on src/cgr_gwas_qc/models/config/workflow_params.py
>      """
should add to the docstring
```
plink: true
```

2025-02-26 16:23 UTC, rajwanir commented
> Nicely done. This adds a nice new feature and the refactoring was much needed. Makes it a lot easier to read and maintain.
> 
> The tests I have conducted show that the new features work as expected.
> 
> Please ensure that we have documentation that details how only the sample_qc subworkflow will execute now if concordance_tools.plink = false.
> 
> Also incorporate a few of the corrections I recommended for the field descriptions. Thanks -j

Updated docs in 5c3554baf3d0889ff7ed08238f693afb5ef648fc. I also reset the defaults for all concordance tools to true so that it runs as all checks as before but it is configurable to skip and save resources/time on larger datasets.

2025-02-26 18:09 UTC, jaamarks approved these changes
LGTM

2025-02-26 18:11 UTC, merged